### ISSUE TITLE
pkg-fetch cannot be built for freebsd, time to switch from pkg-fetch for freebsd?

### ISSUE THREAD

**Issue by srappan** [UnicornTranscoder/UnicornFFMPEG#6]
Unfortunatley, the project seems uninterested to support freebsd further, might be time to switch alternative for the pkg-fetch.

 
> unicorn-ffmpeg@2.2.1 start /root/UnicornFFMPEG
> pkg . -o "bin/Plex Transcoder"

> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-freebsd-x64 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v10.15.3-freebsd-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-freebsd-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-freebsd-x64"}
> Building base binary from source:
  built-v10.15.3-freebsd-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v10.15.3
> Applying patches
> Compiling Node.js from sources...
WARNING: failed to autodetect C++ compiler version (CXX=g++)
WARNING: failed to autodetect C compiler version (CC=gcc)
ERROR: No acceptable C compiler found!
       Please make sure you have a C compiler installed on your system and/or
       consider adjusting the CC environment variable if you installed
       it in a non-standard prefix.
> Error! Error: ./configure failed with code 1
    at ChildProcess.<anonymous> (/root/UnicornFFMPEG/node_modules/pkg-fetch/lib-es5/spawn.js:68:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! unicorn-ffmpeg@2.2.1 start: `pkg . -o "bin/Plex Transcoder"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the unicorn-ffmpeg@2.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1

Github Issues raised on pkg-fetch for this particular issue have gone unanswered

**Comment by Maxou44** [comment]
Do you have ideas about pkg alternatives for freebsd?

**Comment by Maxou44** [comment]
BTW it looks like a compilation issue on your side, try to install gcc / g++ / clang to build the package yourself

**Comment by srappan** [comment]
```
root@plex:~/UnicornFFMPEG # npm start

> unicorn-ffmpeg@2.2.1 start /root/UnicornFFMPEG
> pkg . -o "bin/Plex Transcoder"

> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-freebsd-x64 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v10.15.3-freebsd-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-freebsd-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-freebsd-x64"}
> Building base binary from source:
  built-v10.15.3-freebsd-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v10.15.3
> Applying patches
> Compiling Node.js from sources...
  gmake                        [                    ] 0%
```

Unfortunately now it just stalls. Hasn't progressed for over an hour.

**Comment by Maxou44** [comment]
Maybe use docker could be a great solution for you ? 🥺

**Comment by srappan** [comment]
Possibly, but I actually couldn't find the docker version anywhere 😅

**Comment by Maxou44** [comment]
A "real" docker support is planned in the roadmap 😅

**Comment by srappan** [comment]
Ah thats probably why haha

**Comment by Maxou44** [comment]
You can try this one https://github.com/magn2o/unicorn-docker

**Comment by srappan** [comment]
Thanks! i'll give it ago. I think i'll leave this issue open, just so people don't get stuck on compiling like I did and smashing their heads against their desk till they get a concussion haha
